---
- name: Check Composer File
  slurp:
    src: "{{ drupal_site_dir }}/composer.json"
  register: composer_file_result
- name: Fix Solr API
  command:
    cmd: "composer {{ item }}"
    chdir: "{{ drupal_site_dir }}"
  loop:
    - 'remove drupal/search_api_solr'
    - 'require "symfony/event-dispatcher:4.3.11 as 3.4.41"'
    - 'require drupal/search_api_solr'
    - 'update "symfony/event-dispatcher"'
  when: "'4.3.11 as 3.4.41' not in ( composer_file_result['content'] | b64decode )"